### ISSUE TITLE
grunt compile stopped "undefined is not a function" in json format

### ISSUE THREAD

**Issue by spirau** [rubenv/angular-gettext#173]
I would like to use the lazy-loading option. 
The grunt compile task is working fine with the javascript option:
       nggettext_compile: {
            all: {
                options: {
                    module: 'myApp'
                },
                files: {
                    'app/languages/translations.js': ['po/*.po']
                }
            }
        }

But is aborted due to a warning : "undefined is not a function" when I try the json format:
       nggettext_compile: {
            all: {
                options: {
                    format: "json"
                },
                files: {
                    expand: true,
                    cwd: 'po',
                    src: ['*.po'],
                    dest: 'app/languages', // the trailing slash doen't change anything
                    ext: '.json'
                }
            }
        }
Any idea what is going on?

**Comment by gabegorelick** [comment]
Can you post a stacktrace?

**Comment by spirau** [comment]
Here it is : 
Running "nggettext_compile:all" (nggettext_compile) task
Warning: undefined is not a function Use --force to continue.
TypeError: undefined is not a function
    at D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\file.js:55:29
    at Array.forEach (native)
    at processPatterns (D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\file.js:53:34)
    at Object.file.expand (D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\file.js:110:17)
    at Object.fn [as src] (D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\task.js:180:36)
    at D:\Sites\marip-online\bazi-pro\node_modules\grunt-angular-gettext\tasks\compile.js:14:30
    at Array.forEach (native)
    at Object.<anonymous> (D:\Sites\marip-online\bazi-pro\node_modules\grunt-angular-gettext\tasks\compile.js:13:20)
    at Object.<anonymous> (D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\task.js:264:15)
    at Object.thisTask.fn (D:\Sites\marip-online\bazi-pro\node_modules\grunt\lib\grunt\task.js:82:16)

Aborted due to warnings.

**Comment by gabegorelick** [comment]
Looks like it's in grunt code. What version of grunt are you using? You
probably have something misconfigured.

**Comment by spirau** [comment]
It's v0.4.5. At the moment your tasks are the only one configurated.

module.exports = function (grunt) {

    grunt.initConfig({
        nggettext_extract: {
            pot: {
                files: {
                    'po/template.pot': ['app/templates/*.html', 'app/component/*.js', 'app/main/*.js', 'app/app.js', 'app/index.html']
                }
            }
        },
        nggettext_compile: {
            all: {
                options: {
                    format: "json"
                },
                files: {
                    expand: true,
                    cwd: 'po',
                    src: ['*.po'],
                    dest: 'app/languages',
                    ext: '.json'
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-angular-gettext');

    grunt.registerTask('translate', [
        'nggettext_extract'
    ]);
    grunt.registerTask('compile', [
        'nggettext_compile'
    ])
};
