### ISSUE TITLE
Error when used as directive on angular-ui alert

### ISSUE THREAD

**Issue by varadero** [rubenv/angular-gettext#224]
I'm using angular 1.3.9, angular-ui-bootstrap 0.12.0 and angular-gettext 2.1.0.

If you use translate directive to angular-ui-bootstrap alert like this:

```
<alert type="danger" translate>Login failed: {{vm.data.loginFailDescription}}</alert>
```

you get the following error

```
Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <div ng-transclude="">
http://errors.angularjs.org/1.3.9/ngTransclude/orphan?p0=%3Cdiv%20ng-transclude%3D%22%22%3E
   at link (http://localhost:29471/vendor/angular/angular.js:25109:7)
   at invokeLinkFn (http://localhost:29471/vendor/angular/angular.js:8213:9)
   at nodeLinkFn (http://localhost:29471/vendor/angular/angular.js:7722:11)
   at compositeLinkFn (http://localhost:29471/vendor/angular/angular.js:7075:13)
   at publicLinkFn (http://localhost:29471/vendor/angular/angular.js:6954:30)
   at update (http://localhost:29471/vendor/angular/angular-gettext.js:210:25)
   at post (http://localhost:29471/vendor/angular/angular-gettext.js:223:21)
   at invokeLinkFn (http://localhost:29471/vendor/angular/angular.js:8213:9)
   at nodeLinkFn (http://localhost:29471/vendor/angular/angular.js:7722:11)
   at delayedNodeLinkFn (http://localhost:29471/vendor/angular/angula

```

**Comment by varadero** [comment]
I just want to note a workaround - wrapping translatable content inside <span> like this:

```
<alert type="danger"><span translate>Login failed: {{vm.data.loginFailDescription}}</span></alert>
```

**Comment by varadero** [comment]
It seems that it is caused because ```<alert>``` template contains transcluded part as described in #132  where the suggestion is to wrap translatable content inside ```<span>``` so I will close that issue.
