### ISSUE TITLE
Error: Invalid Argument in IE11

### ISSUE THREAD

**Issue by IlianIliev** [rubenv/angular-gettext#59]
When using interpolation like:

```
<h1 translate>Hello {{ name }}</h1>
```

In IE11 I get the following error:

```
Error: Invalid Argument
 at interpolateFnWatchAction (http://test.com:8080/bower_components/angular/angular.js:6833:15)
   at Scope.prototype.$digest (http://test.com:8080/bower_components/angular/angular.js:12332:23)
   at Scope.prototype.$apply (http://test.com:8080/bower_components/angular/angular.js:12597:13)
   at Anonymous function (http://test.com:8080/bower_components/angular/angular.js:14104:25)
   at completeOutstandingRequest (http://test.com:8080/bower_components/angular/angular.js:4297:7)
   at Anonymous function (http://test.com:8080/bower_components/angular/angular.js:4598:7) undefined
```

The error is shown only If there are variables in the translated text.
Any ideas what is causing it?

**Comment by DOrlov77** [comment]
My solution is to mark the **translate** directive as **terminal**.
See https://github.com/angular-translate/angular-translate/issues/925#issuecomment-77764352

**Comment by gabegorelick** [comment]
@DOrlov77 the [translate directive is terminal](https://github.com/rubenv/angular-gettext/blob/master/dist/angular-gettext.js#L158), although there's an [open PR to change that](https://github.com/rubenv/angular-gettext/pull/147).

**Comment by Shazypro** [comment]
@nikolay-tzonev @DOrlov77 I haven't jumped into the Angular source code too much to see what exactly it's doing, however, just to have some references, this might be a related: https://connect.microsoft.com/IE/feedbackdetail/view/944330/invalid-argument-error-when-changing-nodevalue-of-a-text-node-removed-by-setting-innerhtml-on-an-ancestor#

**Comment by R-Kurbatovvakoms** [comment]
For me it happens again in IE11.

**Comment by henke164** [comment]
For all our customers with IE11, it happens. 
(Its around 1000+ IE11 users)

![image](https://cloud.githubusercontent.com/assets/1499799/14388281/b0e79c74-fdad-11e5-8c49-7eafdc2fbfc9.png)
